extra_css:
- assets/css/custom.css
extra_javascript:
- assets/js/custom.js
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tabbed
- pymdownx.critic
- pymdownx.tasklist
- admonition
- toc
- tables
nav:
- Home: index.md
- Development:
  - GENERATOR: development/docstra/GENERATOR.md
  - pyproject: development/docstra/pyproject.md
  - README: development/docstra/README.md
  - GENERATOR: development/docstra/GENERATOR.md
  - README: development/docstra/README.md
  - pyproject: development/docstra/pyproject.md
- Docstra:
  - repo_map: docstra/.docstra/repo_map.md
  - config: docstra/.docstra/config.md
  - docs_config: docstra/.docstra/docs_config.md
  - __init__: docstra/docstra/__init__.md
  - __init__: docstra/core/__init__.md
  - cli: docstra/core/cli.md
  - app: docstra/core/app.md
  - mkdocs: docstra/docs/mkdocs.md
  - docs_config: docstra/.docstra/docs_config.md
  - config: docstra/.docstra/config.md
  - repo_map: docstra/.docstra/repo_map.md
  - app: docstra/core/app.md
  - cli: docstra/core/cli.md
  - __init__: docstra/core/__init__.md
  - __init__: docstra/docstra/__init__.md
- .Docstra:
  - class_index: .docstra/index/class_index.md
  - symbol_index: .docstra/index/symbol_index.md
  - import_index: .docstra/index/import_index.md
  - function_index: .docstra/index/function_index.md
  - file_index: .docstra/index/file_index.md
  - class_index: .docstra/index/class_index.md
  - symbol_index: .docstra/index/symbol_index.md
  - file_index: .docstra/index/file_index.md
  - function_index: .docstra/index/function_index.md
  - import_index: .docstra/index/import_index.md
- Core:
  - __init__: core/documentation/__init__.md
  - wizard: core/documentation/wizard.md
  - generator: core/documentation/generator.md
  - setup: core/documentation/setup.md
  - __init__: core/ingestion/__init__.md
  - embeddings: core/ingestion/embeddings.md
  - storage: core/ingestion/storage.md
  - local: core/llm/local.md
  - __init__: core/llm/__init__.md
  - openai: core/llm/openai.md
  - anthropic: core/llm/anthropic.md
  - prompt: core/llm/prompt.md
  - ollama: core/llm/ollama.md
  - __init__: core/config/__init__.md
  - wizard: core/config/wizard.md
  - settings: core/config/settings.md
  - __init__: core/utils/__init__.md
  - file_collector: core/utils/file_collector.md
  - chunking: core/document_processing/chunking.md
  - __init__: core/document_processing/__init__.md
  - extractor: core/document_processing/extractor.md
  - parser: core/document_processing/parser.md
  - document: core/document_processing/document.md
  - hybrid: core/retrieval/hybrid.md
  - __init__: core/retrieval/__init__.md
  - chroma: core/retrieval/chroma.md
  - code_index: core/indexing/code_index.md
  - repo_map: core/indexing/repo_map.md
  - __init__: core/indexing/__init__.md
  - wizard: core/documentation/wizard.md
  - setup: core/documentation/setup.md
  - generator: core/documentation/generator.md
  - __init__: core/documentation/__init__.md
  - storage: core/ingestion/storage.md
  - embeddings: core/ingestion/embeddings.md
  - __init__: core/ingestion/__init__.md
  - anthropic: core/llm/anthropic.md
  - openai: core/llm/openai.md
  - ollama: core/llm/ollama.md
  - prompt: core/llm/prompt.md
  - __init__: core/llm/__init__.md
  - local: core/llm/local.md
  - settings: core/config/settings.md
  - wizard: core/config/wizard.md
  - __init__: core/config/__init__.md
  - __init__: core/utils/__init__.md
  - file_collector: core/utils/file_collector.md
  - document: core/document_processing/document.md
  - parser: core/document_processing/parser.md
  - chunking: core/document_processing/chunking.md
  - __init__: core/document_processing/__init__.md
  - extractor: core/document_processing/extractor.md
  - chroma: core/retrieval/chroma.md
  - __init__: core/retrieval/__init__.md
  - hybrid: core/retrieval/hybrid.md
  - code_index: core/indexing/code_index.md
  - repo_map: core/indexing/repo_map.md
  - __init__: core/indexing/__init__.md
- Assets:
  - custom: assets/css/custom.md
  - extra-search-data: assets/js/extra-search-data.md
  - custom: assets/js/custom.md
- Extensions:
  - DocstraToolWindowFactory: extensions/intellij/DocstraToolWindowFactory.md
  - plugin: extensions/intellij/plugin.md
  - CHANGELOG: extensions/vscode/CHANGELOG.md
  - esbuild: extensions/vscode/esbuild.md
  - README: extensions/vscode/README.md
  - package-lock: extensions/vscode/package-lock.md
  - package: extensions/vscode/package.md
  - tsconfig: extensions/vscode/tsconfig.md
  - vsc-extension-quickstart: extensions/vscode/vsc-extension-quickstart.md
  - extension: extensions/vscode/extension.md
- Vscode:
  - reset: vscode/media/reset.md
  - styles: vscode/media/styles.md
  - vscode: vscode/media/vscode.md
  - chat: vscode/media/chat.md
  - extension.test: vscode/suite/extension.test.md
  - chatView: vscode/chat/chatView.md
  - chatManager: vscode/chat/chatManager.md
  - serverManager: vscode/server/serverManager.md
  - installUtils: vscode/utils/installUtils.md
  - workspaceUtils: vscode/utils/workspaceUtils.md
plugins:
- search
- mkdocstrings
site_name: Project Documentation
theme:
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.expand
  - navigation.indexes
  - search.highlight
  - search.share
  - toc.follow
  - content.code.copy
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    accent: indigo
    primary: indigo
